### ISSUE TITLE
Getting thunk-redis to work with callbacks

### ISSUE THREAD

**Issue by masiarb** [thunks/thunk-redis#11]
Hello, I'm sorry for the naïve and probably pointless question, but I really have no time and have to fix a code for a presentation due shortly. I already posted the question on SO (http://stackoverflow.com/questions/33344335/how-to-use-thunk-redis-without-promises), here it goes:

I'm using the thunk-redis library to access my Redis DB and store/retrieve data. I noticed that whenever I call an API function (i.e., client.zadd(...)), it returns a [Function]. Now, I am not an expert in promises, so I'd like to use this library without them, with good ol' callbacks. Is there a way to do it? Here is the example code I'm trying to run:

```
 var addToSortList = function(cb) {
   client.zadd(arguments)(function(err, response) {
      console.log(err, response);
      if(err) throw err;
      if(typeof cb == "function") {
         cb(response);
      }
   });
}
```

The code runs, does not give any error, but the callback function passed to the function returned by .zadd is never executed. What am I doing wrong? How can I execute the callback function?

Thanks.

**Comment by zensh** [comment]
``` js
   client.zadd(arguments)(cb)
```

or 

``` js
client.zadd(arguments)(function(err, res) {
  if (err) throw err
  console.log(res)
  return res
})(cb)
```
