### ISSUE TITLE
Can't use with Redis slave node

### ISSUE THREAD

**Issue by astro** [thunks/thunk-redis#13]
Hi, thank you for creating this fast library.

I'd like to connect to a redis slave node but this line is preventing me from doing so:
https://github.com/thunks/thunk-redis/blob/master/lib/connection.js#L209

Could it be made configurable?

**Comment by zensh** [comment]
Let me check the reason. I will deal with it tonight, thank you for your issue

**Comment by zensh** [comment]
Hi, fixed, with test :1234:
