### ISSUE TITLE
maxAttempts 毫无用处

### ISSUE THREAD

**Issue by xxxman2008** [thunks/thunk-redis#16]
根据 作者 的 文档：白底黑字的文档

options.maxAttempts: Optional, Type: Number, Default: 20.
By default client will try reconnecting until connected. Setting maxAttempts limits total amount of reconnects

1、关于 maxAttempts 的 问题 ：
maxAttempts  ，是否 能 起到作用，如果设置 maxAttempts  为0  ，会不会 禁止 代码 reconnect ？？
请回答 ： 会，还是不会 ？？？？

2、我前面对作者的 代码有过评价，“随处乱抛Error”。。可以参考下面的代码：
如果作者不知道，不熟悉，我可以 提示，是在 connection.js 里面 

if (++this.attempts <= options.maxAttempts) {
this.rescuePending()
this.retryDelay *= 1.2
if (this.retryDelay >= options.retryMaxDelay) {
this.retryDelay = options.retryMaxDelay
}

setTimeout(function () {
  debugSocket('socket reconnecting, %s', ctx.id)
  ctx.connect()
  ctx.redis.emit('reconnecting', {
    delay: ctx.retryDelay,
    attempts: ctx.attempts
  })
}, this.retryDelay)
} else {
this.tryRemove(new Error(this.id + ' reconnecting failed'), true)
}

另外 ，++this.attempts <= options.maxAttempts 本意是判断 是否达到 maxAttempts 的限制。。。OK ，如果达到了 ，那么这是一个程序的 正常 behaviour 。。。作者居然抛 Error ？？？？？ 一个 正常的 ，符合设计目标的行为。。要抛Error？？？
## 不断的 抛ERROR 。。这是 一个正常设计？？？？

和代码无关的事情。

首先，要和作者谈谈做事的态度。
你把代码放到网上供人家参观（此行为公众舆论是鼓励，个人觉得既不用鼓励，也不用打击），既然都公开了，自然就要有 接受批评的 准备。没有人的代码是绝对OK 的，也没有人的代码是绝对垃圾的。

但是，今天，我，没有故意来挑刺，所有我提出的问题，都是有据可查。无可辩驳的。无论你作者是愿意承认，还是不愿意承认 （“哎呀我看不懂你提的问题。。” ）。

这不是一个正确的做事态度。有错，有失误，就认。。2次 close issue ，我相信，你非常非常的清楚我在说什么，可是，你言不由衷的 “我看不懂” 。不愿意承认。
小伙子，这不是一个正确的做事态度。尤其不是一个做技术，精益求精的做事态度。

我老人家恰好有这么个脾气，你不愿意承认也就罢了，2次 close issue ，妄图浑水摸鱼的混过去，我还真就和你认真了。

这个代码，在我看来，就是为了公司里的某一个项目而写，没有做过完整的测试。只是把流程跑通了。而且，写代码之前，也没有完整的规划，一个人写到哪里算哪里。想怎么设计就怎么设计。

这本来其实无可厚非，很多程序员都是这样的。很多公司也都是这样的。但是，很实在的说，我是冲着那句 “已经用于生产环境” 而 npm 的 。结果。。5分钟的测试，就发现了问题。说的轻一点，是文档和代码实现脱节，代码的测试覆盖率不够。说的不好听一点。。呵呵，呵呵。。

**Comment by zensh** [comment]
大神你好

**Comment by xxxman2008** [comment]
顺便说一下 ，你说的IORedis  。。我提交的 issue。。基本上有 90% 的 把握是 一个 bug 。而这个发现，也是5分钟 测试的 结果。

SO，的确，如你所说。。我决定用  node-redis 实现一个 高可用的 私有redis 多主 方案。因为目前，看起来只有 node-redis  代码的强壮性还好一点。

**Comment by zensh** [comment]
挺好，我当时也是觉得 node-redis 不好才造了这个轮子
