### ISSUE TITLE
请问我订阅的消息该如何监听

### ISSUE THREAD

**Issue by alpaca-coco** [thunks/thunk-redis#17]
您好这是我再项目中第一次使用redis，因为是express的项目所以选用了您的这个客户端。我现在有几点疑问麻烦您解答下：
1、当我订阅的到一条数据的时候是不是只能用,redis.on('message',function(channel,count))这个方法来监听。
2,这个监听的方法放在那个层比较好，我希望我的服务一启动的时候就开始订阅部分数据。

希望您看到后解答下  ，谢谢

**Comment by zensh** [comment]
对，就是这个。监听应该放在顶层（全局），而不是中间件层

**Comment by alpaca-coco** [comment]
感谢您的解答！您说的「监听应该放在顶层」，我现在是吧redis监听的模块直接引用到路由里面 ，让他一开始就加载的，不知道您说的放在顶层是怎么样引用的能详细解答下吗？谢谢您
