### ISSUE TITLE
Better transactions or pipeline support?

### ISSUE THREAD

**Issue by AVVS** [thunks/thunk-redis#2]
``` js
            id = shortid.generate();
            return Promise.all([
                // multi-key operations are not allowed in cluster
                client.hsetnx(prefix + id, 'url', url),
                // multi on the same key
                client.multi(),
                client.setnx(key, id),
                client.get(key), // 4.1
                client.exec()
            ]).then(function multiBlockResponse(responses) {
                console.log(responses);
                return responses[4][1].toString('utf-8');
            });
```

> ```
>             return responses[4][1].toString('utf-8');
> ```

This line would result in an from time to time. Reason for this is that commands wont be sent to the server in the desired sequence. Sometimes response would be:

```
[ 1,
  'OK',
  'QUEUED',
  'QUEUED',
  [ 1, <Buffer 63 36 47 58 64 77 43 68 71 69> ] ]
```

Which is what I expect

And sometimes it would be this:

```
[ 1, 'OK', 1, <Buffer 6e 36 61 61 69 48 72 39 47 7a>, [] ]
[ 1, 'OK', 1, <Buffer 63 47 30 34 69 48 72 68 47 30>, [] ]
[ 1, 'OK', 1, <Buffer 6e 71 31 61 64 50 5f 68 53 64>, [] ]
[ 1, 'OK', 0, <Buffer 6e 71 31 61 64 50 5f 68 53 64>, [] ]
[ 1, 'OK', 0, <Buffer 6e 71 31 61 64 50 5f 68 53 64>, [] ]
```

Which means that `multi()` call arrived to the server later than the two subsequent calls, therefore, it's a problem for me - I don't want to wait for response of multi() command before sending the whole command chain, I want the commands to be either buffered and sent in a pipeline, or I want them to be sent in the order they were called, which, should have happened, granted that we have one connection and each command is delayed the same amount of ticks before being sent, however, this is not the case here and it must be dealt with.

Please advise whether I should proceed with my own solution or it should be easy to fix on your side

**Comment by zensh** [comment]
Could you provide more code? I want to test it.

Commands should be sent to the server in sequence. The second result is strange.

Which `Promise` do you use? `Native Promise`?

**Comment by zensh** [comment]
@AVVS Can you try to change code: https://github.com/thunks/thunk-redis/blob/master/index.js#L79 to:

``` js
var thunk = commandMethod.apply(client, arguments)(function(err, res) {
  if (err != null) throw err;
  return res;
});
```

then test it?

**Comment by AVVS** [comment]
bluebird is used

**Comment by zensh** [comment]
I have write a test, no error:

``` js
'use strict';

var assert = require('assert');
var Bluebird = require('bluebird');
var redis = require('thunk-redis');
var client = redis.createClient({
  usePromise: Bluebird
});

client.info().then(function() {
  var time = Date.now();
  var tasks = [];
  for (var i = 0; i < 100000; i++) {
    tasks.push(Bluebird.resolve(i).then(function(x) {
      return Bluebird.all([
        client.get(x),
        client.multi(),
        client.set(x, x),
        client.get(x),
        client.exec()
      ]).then(function (res) {
        // [ '0', 'OK', 'QUEUED', 'QUEUED', [ 'OK', '1' ] ]
        assert(res[1] === 'OK');
        assert(res[2] === 'QUEUED');
        assert(res[3] === 'QUEUED');
        assert(res[4][1] === x + '');
        return res[4][1];
      });
    }));
  }
  Bluebird.all(tasks).then(function(res) {
    console.log(res.length, res[0], res[res.length - 1], (Date.now() - time) + ' ms');
  }).catch(function(err) {
    console.error(err);
  }).then(function() {
    client.quit();
  });
});
```

**Comment by AVVS** [comment]
This is the code that works, you can see commented parts, which didn't work for some reason.
It's used on a production cluster of 15 machines (5 masters + 2 slaves each). If I do the tests locally on the same machine - they pass, when it's done on the production cluster - behaviour is unexpected - sometimes its one thing, sometimes the other. Maybe there is an error in deciding which connection from the cluster to use?

``` js
function generate(opts, next) {

    if (!opts || typeof opts !== 'object') {
        return next(new Error('message must be an object'));
    }

    var url = opts.url;
    if (!url || typeof url !== 'string') {
        return next(new Error('`url` must be specified'));
    }

    var id;
    var key = prefix + url;
    var client = redis();

    return client.get(key)
        .then(function existanceCheck(value) {
            if (value) {
                id = value.toString('utf-8');
                return id;
            }

            id = shortid.generate();
            return Promise.all([
                // multi-key operations are not allowed in cluster
                client.hsetnx(prefix + id, 'url', url),
                // multi on the same key
                // client.multi(),
                client.setnx(key, id),
                client.get(key) //, // 4.1
                // client.exec()
            ]).then(function multiBlockResponse(responses) {
                return (responses[2] || id).toString('utf-8');
            });
        })
        .catch(function (err) {
            logger.error('Error in redis command for key %s:', key, err);
            return Promise.reject(new Error('Cant generate id, redis command'));
        })
        .nodeify(next);

}
```

**Comment by zensh** [comment]
I get the reason: cluster, `client.multi()` and `client.exec()` is sent to a master(default master), while `client.setnx(key, id)` and `client.get(key)` is sent to another master(slot by key hash).

I will fix it in two days

**Comment by AVVS** [comment]
In the cluster mode multi() is to be used on the same keys, so probably it could be a good idea to add some extra checks or buffer commands between multi / exec blocks or require specifying the key in .multi / .exec call. Honestly dont know whats the best solution here

**Comment by zensh** [comment]
Keys hash tags is a way to ensure that multiple keys are allocated in the same hash slot (supported by thunk-redis), http://redis.io/topics/cluster-spec

`client.multi` is another problem -- it don't have key~~

**Comment by AVVS** [comment]
What I mean is that `client.multi()` can be coded to accept a key, for which a hash will be calculated in order to determine which node should the client be sending commands to. Same has to go for .exec call though

**Comment by zensh** [comment]
release v0.8.3:

**cluster transaction:**

``` js
var redis = require('../index');
var client = redis.createClient(7000, {debugMode: false});

client.info()(function*() {
  // provide key to `multi` and `exec` for directing to the same node
  var res = yield [
    this.multi('key'),
    this.set('key', 'key'),
    this.get('key'),
    this.exec('key')
  ];
  console.log(res); // [ 'OK', 'QUEUED', 'QUEUED', [ 'OK', 'key' ] ]

  // Keys hash tags
  res = yield [
    this.multi('hash{tag}'),
    this.set('hash{tag}', 'hash{tag}'),
    this.get('hash{tag}'),
    this.exec('hash{tag}')
  ];
  console.log(res); // [ 'OK', 'QUEUED', 'QUEUED', [ 'OK', 'hash{tag}' ] ]

})();
```
