### ISSUE TITLE
Pipelining support

### ISSUE THREAD

**Issue by abruzzihraig** [thunks/thunk-redis#26]
Hi @zensh ,

I really appreciate the work you did for thunk-redis. Looking through the whole Node.js community, this library is still the best Redis client for me. 

I've tried to find out any clue from your source code to see if it supports pipeline but it is not that obvious to me. Could you pls tell me if your client supports or will support or could support the Redis pipeline feature?

Thanks!

**Comment by zensh** [comment]
Hi, it work as pipelining natively.

**Comment by abruzzihraig** [comment]
Oh that’s great! Thanks.
