### ISSUE TITLE
unix socket support

### ISSUE THREAD

**Issue by AVVS** [thunks/thunk-redis#3]
Hi, it seems there is no unix socket support at the moment.  Any plans on implementing an extra overload on the client constructor to support it?

```
var client = redis.createClient('/tmp/redis.sock', { opts });
```

**Comment by zensh** [comment]
It had been support in old version(<=0.7.x), I removed it for cluster~

**Comment by AVVS** [comment]
Ok, it's not that I really need it, but other modules often rely on it

**Comment by zensh** [comment]
I will try to make it back.
