### ISSUE TITLE
Pub/Sub commands and appropriate events not working

### ISSUE THREAD

**Issue by pashoo2** [thunks/thunk-redis#4]
This example code:

  var redis = require("thunk-redis"),
        client1 = redis.createClient(), client2 = redis.createClient(),
        msg_count = 0;
    client1.on("subscribe", function (channel, count) {
        client2.publish("a nice channel", "I am sending a message.");
        client2.publish("a nice channel", "I am sending a second message.");
        client2.publish("a nice channel", "I am sending my last message.");
    });
    client1.on("message", function (channel, message) {
        console.log("client1 channel " + channel + ": " + message);
        msg_count += 1;
        if (msg_count === 3) {
            client1.unsubscribe();
            client1.end();
            client2.end();
        }
    });
    client1.incr("did a thing");
    client1.subscribe("a nice channel");

from https://github.com/mranney/node_redis works fine with node_redis and does not work with thunk-redis

**Comment by zensh** [comment]
client.publish return a thunk function, it is a lazy evaluation function, so you should chang code:

``` js
client1.on("subscribe", function (channel, count) {
    client2.publish("a nice channel", "I am sending a message.")(function(err, res) {
        // run after publish command finished
        console.log(err, res);
    });
    client2.publish("a nice channel", "I am sending a second message.")(function(err, res) { console.log(err, res); });
    client2.publish("a nice channel", "I am sending my last message.")(function(err, res) { console.log(err, res); });
});
```

**Comment by zensh** [comment]
client1.incr("did a thing")();
client1.subscribe("a nice channel")();

**Comment by zensh** [comment]
example: https://github.com/thunks/thunk-redis/blob/master/test/commands-pubsub.js

**Comment by pashoo2** [comment]
thank you

**Comment by pashoo2** [comment]
This code is working:

``` javascript
 "use strict";
 var redis = require("thunk-redis"),
     client1 = redis.createClient(6379,{usePromise : true}),
     client2 = redis.createClient(6379,{usePromise : true});
client1.on("connect", function(){
   client1.on("message", function(){
       console.log("message1");
       console.log(arguments);
   });
  client1.subscribe("a nice channel")
  .then(function(){
    console.log("sub");    
    client2.publish("a nice channel", "good")
        .then(function(){
            console.log("pub");
        })
        .catch(function(e){
            console.log(e);
        });
  });  
});
```

**Comment by zensh** [comment]
Yes, It is promise API~
