### ISSUE TITLE
MONITOR support

### ISSUE THREAD

**Issue by thelinuxlich** [thunks/thunk-redis#7]
It would be awesome to have a MONITOR endless stream on all nodes!

**Comment by zensh** [comment]
Would you like this way:

``` js
client
  .on('monitor', function(data) {
    console.log(data)
  });
// use `clientSwitch` to change default node
client.clientSwitch('127.0.0.1:7000').monitor()();
client.clientSwitch('127.0.0.1:7001').monitor()();
client.clientSwitch('127.0.0.1:7002').monitor()();
```

But it have a bug, I will fix it.

**Comment by thelinuxlich** [comment]
interesting though I think clientSwitch should be just switch

**Comment by zensh** [comment]
@thelinuxlich `monitor` will monit all master nodes in cluster mode now.

**Comment by thelinuxlich** [comment]
Fantastic!

**Comment by Ace80** [comment]
client.clientSwitch('127.0.0.1:7000').monitor()();
client.clientSwitch('127.0.0.1:7001').monitor()();
client.clientSwitch('127.0.0.1:7002').monitor()();
